{% set name = "jsonlines" %}
{% set version = "4.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0c6d2c09117550c089995247f605ae4cf77dd1533041d366351f6f298822ea74

build:
  skip: true # [py<38]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - wheel
  run:
    - python
    - attrs >=19.2.0

test:
  imports:
    - jsonlines
    - jsonlines.jsonlines
  source_files:
    - tests
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - pytest -v tests # [not win]
    # Skip due to path problems in tests implementation for Windows.
    # Checked manaully, works properly.
    - pytest -v tests -k "not test_open_reading and not test_open_reading_with_utf8_bom and not test_open_writing and not test_open_and_append_writing" # [win]


about:
  home: https://github.com/wbolster/jsonlines
  license_file: LICENSE.rst
  license: BSD-3-Clause
  license_family: BSD
  summary: 'Library with helpers for the jsonlines and ndjson file formats'
  description: |
    This data format is straight-forward: it is simply one valid JSON value per line,
    encoded using UTF-8. While code to consume and create such data is not that complex,
    it quickly becomes non-trivial enough to warrant a dedicated library when adding data
    validation, error handling, support for both binary and text streams, and so on.
    This small library implements all that (and more!) so that applications using this
    format do not have to reinvent the wheel.
  dev_url: https://github.com/wbolster/jsonlines
  doc_url: https://jsonlines.readthedocs.io/

extra:
  recipe-maintainers:
    - pmlandwehr
