travis:
  secure:
    BINSTAR_TOKEN: dpP/yfhyQfelH2PT9QEXgW9B5A+n1Zye4sM1sM+HXKYE/LjeF5vn5fXOaAxzB5dgo1lg5jBtyCUbm8d44wPc5Iy+lm7z8gICF/KxDlDi7rUjYD5KRyun06W746Jrcrq84J/piCIXsmuOhhvgF4IF3lwoKuuLS0fPJykbNQ/Dyh+M1zO6wOj4/Xt+LpvZlnW32FsPsu+Q0IBzPErBAaH2u8Lm83a/x0T999psjLkwAbl9xkSAXFQBaOMt1+pVNWh71nX38EZrUTg42Clf7a+edKRvkeKQibt0PpcEm2qtlVv+JUeSOxqS9L2BjbUHVMMUP/LJgstppUwR/yggdkUPsFV5aSYOSHmNle3KgecLTMdwyWaOTWY0nxtzG3vBO108i5IAoouSqVXPgjsEMgywiY4yeVdOfqPsdtGx+/O+eea9TaIvVA+Pqqka/PhuWAzbz7LK8nqufFke8jJ7V7LCqkcTsq/vxoJZ/bo4WSlaHxJW8o2qA1yrC2ewHNCMbB4LwmDTK0gqSS3z+sC3Q2jTBQEMsCv5Gw6B/2nac63bhKvl3A+N4R2PTa4qY07O4xw9Krnt9r1Zubqfy073bK3S7EJtMUoDMXYt8chgY2yjQY6TzwGiTz4ePG90wkZYhDJulwMcaWC6BPsvOq2DVbbJD0cIKsW0+sV1A95UKD7GGPY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
