travis:
  secure:
    BINSTAR_TOKEN: XkXJPytUJeFe2btDLfSxjqcid0/3GhZ67IDVIVSOE/jqL5QOSZAANu0SWnG6nhKRyND5pcWPNfph6OW2JvJmVruhhRhbSnNKrtQcggR4c7yXh8xrVGZ0F+ZZizlp0nJTsPFjjbM5cJ+0dciSvSBt66aya26gH6KMhtEOie3jSV08lFkVhm0cGIXJqX3WuSDaPZLn4QL2EvbaZmlK9xNRYZUwE/FXzzvXRC333cmkH+27MoCbfduPZsg25O5HFhmx39Ye1nEUGu+7mUptjB3s9+YQaQfHrYDZ3XZf7Xa0WjZPFm0XHha1u2bIj7AEIzmRvU4bhLSgsC6KViAvFdYMxnZzB7ts4y2CJcHYSp5IoaYjwqulRHA6w60bY9u3NUv3spz1oAb5md8RmnZYKbMInfMmPQAGRcKA+kO+3UQGja5ODeIYGSdsvEunIN6saocbmMfivWD739p6gw2NUmTBzKtdhrtPQQgNDcSlf3CoZb2XXqEmX9abVw3/BMRumoSJv8as8pqj1RcIHiQ+MYyLJ3aC2QvBFdbwuhbHZ74nnDpr0XxIBzJu947FtUOTIv1hbGkb0q2sy9HpAg3bm/DZJp0Ms9baveIP+Ea6HlrcUCoQfTv5EhLirWwNEC3kBkfu/0QzeUFEPVTtVpPgi+wQ7YhmTc/3WbPuflxebTRAJ8M=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
