travis:
  secure:
    BINSTAR_TOKEN: STFp94pUR7EjEjAhws27NefzDAjV+1dXTVelfQ1h9sRgZ1s8uobxN9kCSy91W8/zu77+56sTedPpxgvHUQMvhC8g8UB7S0GGI8zvCOUQOoJZHOZ9s3N01KkO2QP6txQwo7wLX930tJukjOpv0MLsEX0m9lpMQStU6o908Hn2tF3r/DpYXShunNXUZOGP7voMhXF/Fk3R6PVMGHk0Rw7CH+zx8yVcwO0nMS6KeF9d1yTAJwVyDW3wKzWBkYS72ugRVhGm1adOUAtCtc3+EOzvE1SLf4f6zJ5PnCKLXK7ofTlQDoc9AJirnKV/s4uKxWPvB3n9mS6b64nFTJQVZJPUNyPiYiNTVzYQrVmopbmf0E+mph9NlbaUeAoeTrWtpbbiIvtL983nlekiNghvBioNa3qaHqLOeABPY5yxcVxv7PurmL8vdxESj18hP95HgxFjiuyOviryJYfknMv0PFWvnsxB/1RquXutQ6JLfHdB52m4MFXkXHWzYoq0vC2OOG3SP1N5S0wKyO67qHwehwWP05Haq197Gn4fmYcqkiKRt9diJUf5/OnP+E0HoBdzxMKIUwTGWS/mvQ/Jskr+zIt+qc2z+12Mypsdy9/F1QQTWVdGeMjFPNXrfsTbMYszqcL0mK3F+8Tjq4oZx2HBhEqisD4hbjV46i96mV2IGW409R8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
